### PR TITLE
[API] Create createItinerary Function

### LINKED ISSUE #40: [API] Add the ability to create a Itinerary for a player.
The two main ways I can think of for implementing this would be to either:
1. Add a function to the Journey(Bukkit?)API that  takes a `JourneyPlayer`/`Player` and an destination, either `Cell` or `Location`, then creates a `PlayerDestinationGoalSearchSession` for that player.
2. Add a function onto `JourneyPlayer` that allows you to specify a destination (probably `Cell`) to navigate to.

Either way it's probably a good idea to add a way to fetch a `JourneyPlayer`.

### PR DESCRIPTION
**Pull request by TheDeafCreeper**
The goal of this pull request is to allow developers to create an itinerary for a player via the API.
(Resolves #40 )

Currently I:
1. Add `toJourneyPlayer` to the `JourneyBukkitAPI` and `BukkitUtil`.
2. Add `createItineraryTo` to `JourneyPlayer`.

### CODE REVIEW

**Comment by TheDeafCreeper** [comment]
I've never made an API before so I have no idea how to actually set this up to test it.

**Comment by TheDeafCreeper** [comment]
Alright tested API and it works.

**Review by whimxiqal — COMMENTED** [review]
I'm going to have to think about this some more. I don't love the `createItinerary` as a function of the `JourneyPlayer` since that's really just supposed to be a source of information about a player and not a starting point for any sort of logic execution.

Also, the actual interface can be a lot more generalized. For instance, I'd like people to be able to create "itineraries" (probably called something a little more developer-friendly, like just "Path", even though that's used differently internally) for not just players, but also given an arbitrary set of available modes.

**Comment by TheDeafCreeper** [comment]
I think having methods that act on a player would be intuitive to have on that player instead of having to do something like `createPath(player, origin, dest)`.

Being able to do more advanced stuff by making a path manually would also be nice, but 90% of the time devs are probably going to just want to tell a player how to walk from point a to point b.

**Comment by whimxiqal** [comment]
Another big integration I have planned is for Citizens, so I want for devs to be able to execute a search for an NPC given a set list of modes that the NPC should be expected to use, and then the NPC can act as a guide instead of the path search for the player

**Comment by whimxiqal** [comment]
And about your point about the `JourneyPlayer`, there's no need to get an entire `JourneyPlayer` when all you need to identify a a player is their UUID. So I'd be imagining something like 
```java
Future<SearchResult> calculateDestinationPath(CalculationSettings settings, Cell origin, Cell destination);

Future<SearchResult> calculateDomainPath(CalculationSettings settings, Cell origin, int domain);

CalculationSettings playerSettings(UUID playerUuid, boolean display);
```

And you would use it like:
```java
CalculationSettings playerSettings = journeyApi.playerSettings(myPlayer, true);
journeyApi.calculateDestinationPath(playerSettings, origin, destination);  // ignore future if you don't want to use it
```

or, if you just want to calculate the path for your own dev purposes:
```java
CalculationSettings playerSettings = journeyApi.playerSettings(myPlayer, false);
Future<SearchResult> searchFuture = journeyApi.calculateDestinationPath(playerSettings, origin, destination);  // using future

// in a repeated task
if (searchFuture.isDone()) {
  // Use the resulting path for whatever purposes you have, like using a custom displaying mechanism
  myDisplayMethod(searchFuture.get().getPath());

  // Or maybe you just wanted to know how far away it was
  audience().sendMessage("The path is " + searchFuture.get().getLength() + " blocks away");
}
```

and finally, if you wanted to have an NPC follow a path, or just do something different uninvolving of a player:
```java
CalculationSettings npcSettings = new NpcCalculationSettings(/* args */);  // your own custom settings
Future<SearchResult> searchFuture = journeyApi.calculateDestinationPath(npcSettings, origin, destination);  // using future

// in a repeated task
if (searchFuture.isDone()) {
  myGuideMethod(searchFuture.get().getPath());
}

```
What do you think?

**Comment by whimxiqal** [comment]
Closed in favor of API changes added in v1.1

**Pull request closed without merging**
